/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#fabc46",
        "on-primary-container": "#ac9181",
        "on-secondary-container": "#342800",
        "background": "#131313",
        "on-secondary-fixed-variant": "#574500",
        "primary-fixed-dim": "#dec1af",
        "on-surface-variant": "#d2c4bc",
        "on-secondary": "#3c2f00",
        "on-error": "#690005",
        "tertiary-fixed": "#ffdeab",
        "secondary-container": "#af8d11",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#271900",
        "surface-container": "#20201f",
        "surface": "#131313",
        "secondary-fixed-dim": "#e9c349",
        "on-secondary-fixed": "#241a00",
        "outline": "#9b8e87",
        "secondary": "#e9c349",
        "primary-fixed": "#fbddca",
        "surface-container-highest": "#353535",
        "tertiary": "#fabc46",
        "surface-variant": "#353535",
        "error-container": "#93000a",
        "on-tertiary": "#422c00",
        "surface-tint": "#dec1af",
        "secondary-fixed": "#ffe088",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#c48c15",
        "on-primary-fixed": "#28180d",
        "surface-container-high": "#2a2a2a",
        "tertiary-container": "#402b00",
        "error": "#ffb4ab",
        "surface-bright": "#393939",
        "surface-container-low": "#1c1b1b",
        "inverse-primary": "#705a4c",
        "primary-container": "#3d2b1f",
        "outline-variant": "#4f453f",
        "on-tertiary-fixed-variant": "#5f4100",
        "surface-container-lowest": "#0e0e0e",
        "primary": "#dec1af",
        "inverse-on-surface": "#313030",
        "on-primary": "#3f2c20",
        "on-primary-fixed-variant": "#574335",
        "on-background": "#e5e2e1",
        "on-error-container": "#ffdad6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "64px",
        "stack-sm": "12px",
        "margin-mobile": "20px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "unit": "8px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "button": ["Montserrat"],
        "display-lg": ["Playfair Display"],
        "headline-lg-mobile": ["Playfair Display"],
        "body-md": ["Montserrat"],
        "headline-lg": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "label-caps": ["Montserrat"]
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "button": ["14px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
